/*
# Reconcile migrations with actual production database state

این فایل یک snapshot کامل و به‌روز از وضعیت واقعی دیتابیس است که جایگزین migration های
قدیمی و ناقص قبلی می‌شود. جدول‌ها و توابعی که پیش‌تر مستقیماً در پنل Supabase ساخته شده
بودند (بدون ثبت در migration) اینجا مستند می‌شوند.

1. جدول‌ها
- projects: پروژه‌های ثبت‌شده توسط کارفرما/مدیر (شامل ستون manager_code که در migration قبلی نبود)
- baselines: برنامه‌ی زمان‌بندی مبنا (Baseline) هر پروژه، به‌صورت JSON در wbs_data
- responses: گزارش‌های روزانه‌ی دریافتی از تلگرام، همراه با task_code/percent_complete/ai_summary
  که توسط تحلیل هوش مصنوعی پر می‌شوند
- analysis_reports: خروجی تحلیل‌های هوش مصنوعی (مبنا و انحرافات)
- blockers: موانع فعال/برطرف‌شده‌ی هر فعالیت

2. امنیت (RLS)
- Row Level Security روی همه‌ی جدول‌ها فعال است.
- هیچ Policy عمومی برای خواندن/نوشتن مستقیم تعریف نشده است.
- تمام دسترسی خواندن از طریق توابع SECURITY DEFINER زیر انجام می‌شود که هرکدام فقط
  داده‌ی مرتبط با project_code ورودی را برمی‌گردانند.
- نوشتن (insert/update) توسط n8n با کلید service_role انجام می‌شود که به‌طور پیش‌فرض
  از RLS عبور می‌کند.

3. توابع امن (SECURITY DEFINER)
- create_project: ساخت پروژه‌ی جدید و تولید خودکار manager_code
- get_project_by_code: خواندن پروژه بر اساس کد پروژه (برای اعضای تیم)
- get_project_by_manager_code: خواندن پروژه بر اساس کد مدیر
- get_baseline_by_project: خواندن Baseline یک پروژه
- get_responses_by_project: خواندن گزارش‌های یک پروژه
- get_blockers_by_project: خواندن موانع یک پروژه
*/

-- ============================================================
-- 1. جدول‌ها
-- ============================================================

CREATE TABLE IF NOT EXISTS public.projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_name text,
  client_name text,
  project_code text NOT NULL UNIQUE,
  manager_code text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.baselines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  project_code text NOT NULL,
  wbs_data jsonb
);

CREATE TABLE IF NOT EXISTS public.responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  telegram_id text,
  username text,
  message text,
  "Project_id" text,
  task_code text,
  percent_complete numeric,
  ai_summary text
);

CREATE TABLE IF NOT EXISTS public.analysis_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_code text NOT NULL,
  single_page_summary text,
  detailed_report text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blockers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_code text NOT NULL,
  task_code text,
  title text NOT NULL,
  severity text NOT NULL DEFAULT 'Medium',
  status text NOT NULL DEFAULT 'open',
  reported_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  impact text
);

-- ============================================================
-- 2. فعال‌سازی RLS بدون هیچ Policy عمومی
-- ============================================================

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.baselines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analysis_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blockers ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 3. توابع امن (SECURITY DEFINER)
-- ============================================================

CREATE OR REPLACE FUNCTION public.create_project(
  p_project_name text,
  p_client_name text,
  p_project_code text
)
RETURNS TABLE(id uuid, project_code text, manager_code text)
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  INSERT INTO public.projects (project_name, client_name, project_code, manager_code)
  VALUES (
    p_project_name,
    p_client_name,
    p_project_code,
    'MGR-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8))
  )
  RETURNING id, project_code, manager_code;
$function$;

CREATE OR REPLACE FUNCTION public.get_project_by_code(p_code text)
RETURNS TABLE(id uuid, project_name text, client_name text, project_code text)
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT id, project_name, client_name, project_code
  FROM public.projects
  WHERE project_code = p_code;
$function$;

CREATE OR REPLACE FUNCTION public.get_project_by_manager_code(p_code text)
RETURNS TABLE(id uuid, project_name text, client_name text, project_code text)
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT id, project_name, client_name, project_code
  FROM public.projects
  WHERE manager_code = p_code;
$function$;

CREATE OR REPLACE FUNCTION public.get_baseline_by_project(p_project_code text)
RETURNS SETOF public.baselines
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select * from public.baselines where project_code = p_project_code;
$function$;

CREATE OR REPLACE FUNCTION public.get_responses_by_project(p_project_code text)
RETURNS SETOF public.responses
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select * from public.responses where "Project_id" = p_project_code;
$function$;

CREATE OR REPLACE FUNCTION public.get_blockers_by_project(p_project_code text)
RETURNS SETOF public.blockers
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select * from public.blockers where project_code = p_project_code;
$function$;

GRANT EXECUTE ON FUNCTION public.create_project(text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_project_by_code(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_project_by_manager_code(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_baseline_by_project(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_responses_by_project(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_blockers_by_project(text) TO anon, authenticated;
